export const SECTIONS = {
  LISTENING: "listening",
  READING: "reading",
  WRITING: "writing",
  SPEAKING: "speaking",
};

export const SECTION_ORDER = [
  SECTIONS.LISTENING,
  SECTIONS.READING,
  SECTIONS.WRITING,
  SECTIONS.SPEAKING,
];

export const SECTION_DURATIONS_SECONDS = {
  [SECTIONS.LISTENING]: 30 * 60,
  [SECTIONS.READING]: 60 * 60,
  [SECTIONS.WRITING]: 60 * 60,
  [SECTIONS.SPEAKING]: 15 * 60,
};
